@include('layout.header')
<div id="kt_content" class="content d-flex flex-column flex-column-fluid"><div id="kt_post" class="post d-flex flex-column-fluid"><div id="kt_content_container" class="container-fluid">
<div class="card mb-5 mb-xl-8"><div class="card-header border-0 pt-5"><h3 class="card-title align-items-start flex-column"><span class="card-label fw-bolder fs-3 mb-1">Transações</span><span class="text-muted mt-1 fw-bold fs-7">Negociações entre empresas</span></h3><div class="card-toolbar"><a href="{{ route('transacoes.create') }}" class="btn btn-sm btn-light-primary">Nova Transação</a></div></div>
<div class="card-body"><div class="table-responsive"><table class="table table-row-bordered align-middle gs-0 gy-3"><thead><tr class="fw-bolder text-muted bg-secondary"><th class="ps-4">Resíduo</th><th>Origem</th><th>Destino</th><th>Status</th><th>Data</th><th class="text-end pe-4">Ações</th></tr></thead><tbody>
@forelse($transacoes as $transacao)
<tr><td class="ps-4">{{ optional($transacao->residuo)->tipo_material }}</td><td>{{ optional($transacao->empresaOrigem)->nome }}</td><td>{{ optional($transacao->empresaDestino)->nome }}</td><td>{{ ucfirst($transacao->status) }}</td><td>{{ optional($transacao->data_transacao)->format('d/m/Y') ?: '-' }}</td><td class="text-end pe-4"><a href="{{ route('transacoes.show', $transacao->id) }}" class="btn btn-sm btn-light-info">Ver</a> <a href="{{ route('transacoes.edit', $transacao->id) }}" class="btn btn-sm btn-light-primary">Editar</a> <form method="POST" action="{{ route('transacoes.destroy', $transacao->id) }}" class="d-inline form-excluir">@csrf @method('DELETE')<button class="btn btn-sm btn-light-danger">Excluir</button></form></td></tr>
@empty <tr><td colspan="6" class="text-center py-8 text-muted">Nenhuma transação cadastrada.</td></tr> @endforelse
</tbody></table></div>{{ $transacoes->links() }}</div></div></div></div></div>
@include('layout.footer')<script>$('.form-excluir').on('submit',function(e){e.preventDefault();var f=this;Swal.fire({title:'Excluir transação?',icon:'warning',showCancelButton:true,cancelButtonText:'Cancelar',confirmButtonText:'Sim, excluir'}).then(function(r){if(r.isConfirmed)f.submit();});});</script>@include('painel.shared.alerts')</body></html>
